### ISSUE TITLE
Create virtual environment using poetry

### ISSUE THREAD

**Issue by HenriqueAJNB** [camilaccb/Automation-read-invoices#2]
- What is a virtual environment?
- Which tools can be used to create a python virtual environment?
- Read the poetry documentation: https://python-poetry.org/

The main goal is to create a virtual environment to start the project.

**Comment by camilaccb** [comment]
- A virtual environment is a Python environment such that the Python interpreter, libraries and scripts installed into it are isolated from those installed in other virtual environments
- Virtual environment has its own pip to install libraries, its own libraries folder, where new libraries are added, and its own Python interpreter for the Python version you used to activate the environment. The application becomes "self contained".
- Benefits: the project become isolated and is not interfered by other changes, become more easy to share and to be replicated by other developers

  [Source1](https://www.freecodecamp.org/news/how-to-setup-virtual-environments-in-python/#:~:text=Python's%20official%20documentation%20says%3A%20%22A,one%20which%20is%20installed%20as)

- In general on virtual env for each project 
- Requirement file -> Pip install -> All dependencies installed 
- Poetry proposal:

![image](https://user-images.githubusercontent.com/98741510/207465251-91b8919f-51e3-46a2-b81f-07a2b2726866.png)
 

-Passo a passo para instalar o poetry:
1. Instalar no sistema
curl -sSL https://install.python-poetry.org | python3 -
![image](https://user-images.githubusercontent.com/98741510/207466243-11163441-28f3-42d7-9f3d-fe7ac4257f3e.png)

2. Add poetry to a PATH 

Reason:

![image](https://user-images.githubusercontent.com/98741510/207474098-41466af5-8411-45e1-b788-8248da7727c4.png)


3. Use poetry

![image](https://user-images.githubusercontent.com/98741510/207466512-d891d736-fdc6-4112-addc-4423608f0b99.png)

 4. Create a project
 poetry new poetry-demo
![image](https://user-images.githubusercontent.com/98741510/207467304-6ec778ad-4e1c-4dcf-a495-031ec5c6173f.png)

 5. Add dependencies
 Modifying the pyproject.toml file by hand or use a command

![image](https://user-images.githubusercontent.com/98741510/207467727-04453015-3df3-436c-9bb3-4ed60e1cdad8.png)

![image](https://user-images.githubusercontent.com/98741510/207467750-297f903e-5f7d-446b-9432-200ed0388797.png)

6. Update dependencies

![image](https://user-images.githubusercontent.com/98741510/207469147-02dff2f1-5446-4b1c-88a8-ec1dd395db46.png)

(Quando o pacote estiver pronto)

7. Gerar pacote

git init 
git add (nome do projeto)
poetry build
poetry export -f requeriments.txt -o requirements.txt

[Source2](https://www.youtube.com/watch?v=_XszPRFHQQ4) 
[Source3](https://www.youtube.com/watch?v=Xf8K3v8_JwQ)

**Comment by camilaccb** [comment]
@HenriqueAJNB  Quando fui instalar o poetry pelo prompt ele não aceitou a referência de python 3 como sugerida na documentação. Isso tem algum problema? Eu consegui fazer ele encontrar a referência quando mudei o nome do executável do python na pasta em que ele está localizado, mas não sei se é essa a solução mas adequada pra ele encontrar o python 3 

![image](https://user-images.githubusercontent.com/98741510/207572895-6a190487-b28b-433d-b275-749c6ed948c1.png)

![image](https://user-images.githubusercontent.com/98741510/207573121-0a79d326-7582-40e9-8c92-8b8c93e392be.png)

Local onde eu mudei o nome do executável e como ficou no prompt:

![image](https://user-images.githubusercontent.com/98741510/207575494-43f18529-baa0-4a6e-801f-2cdcbb1f2619.png)

![image](https://user-images.githubusercontent.com/98741510/207575944-4a276470-5224-4af3-ab54-a9699144dc7a.png)

**Comment by HenriqueAJNB** [comment]
@camilaccb, se você olhar com calma, essa parte falando sobre `python` e `python3` é referente ao Linux, MacOS e o WSL. A sigla WSL significa Windows Subsystem Linux. É um terminal dentro do Windows parecido com o terminal do Linux. Você pode ler mais sobre ele [aqui](https://learn.microsoft.com/en-us/windows/wsl/install).

No Windows "comum", que creio ser o seu caso, você pode instalar o `poetry` com o `pip` usando o comando abaixo:
```bash
pip install poetry
```

Não sei o motivo de a instalação com `pip` não estar na documentação, mas o `poetry` está no repositório aberto e oficial de pacotes do Python, o PyPI. Dá uma olhada [aqui](https://pypi.org/project/poetry/).

---

E sobre a alteração que você fez de mudar o nome do executável, eu não recomendo fazê-la no Windows. Explico o motivo abaixo:

Quando você instala o Python no Windows, o nome padrão dele é `python`. Se você alterar o nome, você pode quebrar as outras referências que usam `python.exe` e não `python3.exe`.

## Porque existe `python` e `python3` então?
As versões anteriores das distribuições Linux vinham com o python 2 instalado por padrão. O próprio sistema operacional usava e ainda usa o python. Quando o sistema migrou para o python 3, ficou da seguinte forma:
- o comando `python` aponta para o interpretador do sistema operacional. Este não deve ser usado. A adição/atualização/remoção de pacotes neste interpretador pode afetar e até corromper o sistema operacional como um todo.
- A instalação de outro interpretador python no Linux aponta para o `python3`.

Essa alteração é para simplesmente isolar o python do sistema operacional. Desta forma, `python` refere-se ao interpretador nativo do sistema operacional e `python3` aponta para outros interpretadores instalados.

A recomendação **para sistemas Linux e MacOS** é usar sempre o `python3`.

No seu caso, como você usa Windows, não vejo porque alterar o nome do executável. Basta instalar o `poetry` normalmente com expliquei acima.

**Comment by camilaccb** [comment]
Perfeito, entendi a explicação!

**Comment by camilaccb** [comment]
@HenriqueAJNB Mais algumas dúvidas que tive:

- O poetry só é utilizado pra fazer o gerenciamento de dependências externas? Por acaso tentei fazer um `poetry add` de uma biblioteca nativa do python e não funcionou.

- Só pra eu entender se estou no caminho certo:  ideia é que eu consiga publicar o pacote do meu projeto e qualquer outra pessoa consiga instalar esse pacote de dependências utilizando o `pip install`? Estudei um pouco e vi que posso utilizar o `Pypi` pra alcançar esse objetivo .

**Comment by HenriqueAJNB** [comment]
> O poetry só é utilizado pra fazer o gerenciamento de dependências externas? 

De fato o `poetry` só é usado para gerenciar dependências externas. Mesmo porque o que é interno não é uma dependência. Acho que você confunde ainda o `pip install` com o `import`. Vou esclarecer aqui embaixo:

Instalar uma dependência externa é trazer ela de algum lugar da internet (repositório do GitHub, PyPI, etc.) para sua máquina local. Aqui você precisa de conexão com internet pra fazer o download da dependência. As dependências são instaladas com `pip install`, caso você esteja usando o `pip`, ou com `poetry add`, caso use o `poetry`.

Uma vez que a dependência está instalada na sua máquina, você precisa importá-la para o seu projeto. Você só consegue importar dependências que estão instaladas. É o famoso `import <nome_da_lib>`. 

> Por acaso tentei fazer um poetry add de uma biblioteca nativa do python e não funcionou.

E não deveria mesmo. Se é uma biblioteca nativa do python, basta você importar. Quando você instala o python, ela já foi instalada na sua máquina.

> Só pra eu entender se estou no caminho certo: ideia é que eu consiga publicar o pacote do meu projeto e qualquer outra pessoa consiga instalar esse pacote de dependências utilizando o pip install? Estudei um pouco e vi que posso utilizar o Pypi pra alcançar esse objetivo .

Não pensei em publicar não. Publicar tem a ver com a pessoa fazer uso do seu projeto, e para as pessoas usarem, basta o bot estar disponível. Ninguém precisará nem tocar no seu código. A ideia de manter uma lista de dependências tem muito mais a ver com a colaboração de desenvolvimento. Se eu for te ajudar a desenvolver (e não usar) o seu projeto, eu preciso saber quais dependências eu preciso instalar.

**Comment by camilaccb** [comment]
@HenriqueAJNB Entendi. Essa diferença do `pip install `para o `import` eu já tinha entendido direitinho. 
Sobre a publicação compreeendi a sua explicação e do porque não é necessário. 

Bom, então basicamente a eu vou desenvolver o meu código dentro da pasta que foi criada quando eu fiz um `poetry new invoice-reader`? Assim sempre que eu fizer os commits e tiver atualizado dependências usando o poetry, essa lista fica atualizada. Vou subir essa pasta aqui no github.

![image](https://user-images.githubusercontent.com/98741510/208198660-4a60ee23-3f72-4502-9f61-8fc6da086148.png)

**Comment by camilaccb** [comment]
@HenriqueAJNB percebi a partir da aula de hoje de manhã sobre ambientes virtuais que a minha pasta` .venv `não estava na pasta do projeto e que também quando abria no vs code ele estava utilizando o python global acredito que por conta dessa configuração. Então configurei o `virtualenvs.in-project = true`

![image](https://user-images.githubusercontent.com/98741510/208267418-491e188a-0c1a-409b-8aaf-f0a897d4f7b6.png)

Agora tenho a seguinte configuração:

![image](https://user-images.githubusercontent.com/98741510/208267461-0abe83a1-2013-471a-88a2-bbd079012ff3.png)

E no arquivo `main.py` tenho o python do ambiente virtual:

![image](https://user-images.githubusercontent.com/98741510/208267498-9fadfa89-a14a-472e-9b7d-afc5725f1b46.png)

**Comment by HenriqueAJNB** [comment]
Maravilha @camilaccb. Só algumas ressalvas em relação à organização do seu projeto, que por sinal está ótima já:

- Na pasta raiz do projeto não é comum colocarmos scripts. Normalmente ficam só arquivos de configuração e documentação
- Para alocar os scripts, você tem 2 opções:
   - Criar uma pasta chamada `src` no repositório, e todos os scripts ficarão nela. O nome `src` vem de _source_, que são os arquivos fonte do seu projeto. Isso é comum em outras linguagens nas quais você precisa compilar o código fonte.
   - Criar uma pasta com o mesmo nome do repositório, só substituindo o traço (`-`) por underline (`_`). 
- Quando você for importar o seu projeto, você sempre importa o pacote com o nome desta pasta acima que você criou. Exemplos:

Dentro do _src/main.py_:
```python
from src import <outros_modulos>
```

Caso você opte pelo nome da pasta igual ao nome do repositório _automation_read_invoice/main.py_:
```python
from automation_read_invoice import <outros_modulos>
```

O nome que você escolheu é bastante longo, e não é tão comum assim. Mas não é um problema. Você pode criar a pasta com o nome que você quiser. O comum é seguir o que falei nos tópicos acima. Você pode criar uma pasta, por exemplo, _air_, com as iniciais do repositório.

Existe a [PEP 423](https://peps.python.org/pep-0423/) que diz sobre boas práticas na criação e nomeação de pastas, módulos, pacotes e scripts. Mas pouca gente a conhece, e não é tão importante segui-la a risca.

**Comment by HenriqueAJNB** [comment]
E outro detalhe ali sobre a pasta `.venv`. Primeiro parabéns por buscar na documentação do `poetry` como criar o ambiente na própria pasta do projeto. Isso é muito útil e ajuda a isolar mais ainda o ambiente, evitando confusão em relação à qual ambiente é de qual projeto.

A única ressalva aqui é que o `.venv` não deve subir para o repositório do GitHub, uma vez que ele será criado quando a pessoa baixar o projeto e instalar tudo que é necessário com o comando `poetry install`.

Para dizer ao `git` que ele deve ignorar simplesmente tudo que está nessa pasta, você pode usar o arquivo `.gitignore`, cuja documentação pode ser encontrada [aqui](https://git-scm.com/docs/gitignore).

Em resumo, é um arquivo no qual você vai colocar tudo que o `git` vai ignorar. No arquivo `.ignore`, basta você acrescentar a pasta `.venv` que automaticamente tudo que for modificado, alterado ou removido não será rastreado pelo `git` quando você subir o arquivo `.gitignore` com o nome da pasta a ser ignorada.

**Comment by camilaccb** [comment]
Dicas valiosas, implementado!

**Comment by HenriqueAJNB** [comment]
Visto que você já concluiu essa parte, podemos encerrar esse issue e passar o card lá no projeto pra concluído! 

Mais uma vez parabéns!
