### ISSUE TITLE
Create Telegram bot

### ISSUE THREAD

**Issue by camilaccb** [camilaccb/Automation-read-invoices#3]
- How does a bot telegram works?
- What is needed to create a telegram bot?

Useful links:
- https://learn.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-telegram?view=azure-bot-service-4.0

Final goal: have a bot created in Telegram.

**Comment by camilaccb** [comment]
Bot created: t.me/invoice_reader_bot

**Comment by HenriqueAJNB** [comment]
Você anotou seu token? Você vai precisar dele quando for conectar com python

**Comment by camilaccb** [comment]
Anotei sim!
