### ISSUE TITLE
Connect created bot with Python

### ISSUE THREAD

**Issue by camilaccb** [camilaccb/Automation-read-invoices#4]
- Install `python-telegram-bot` in the virtual environment. 
- Create a simple app that repeats the same message received by a user.

https://github.com/python-telegram-bot/python-telegram-bot

**Comment by camilaccb** [comment]
Documentation:

https://core.telegram.org/bots/tutorial
https://core.telegram.org/api

**Comment by camilaccb** [comment]
@HenriqueAJNB Tive um pouco de dificuldade quando fui direto na documentação do python-telegram-bot então estou tentando dar um passo atrás e entender melhor a api do telegram e o próprio funcionamento de api.

**Comment by HenriqueAJNB** [comment]
Oi @camilaccb. É normal ter essas dificuldades a partir de agora.

## sobre APIs
Sobre APIs eu sugiro você dar uma olhada nessa documentação [aqui](https://www.redhat.com/en/topics/api/what-are-application-programming-interfaces). Tente captar a ideia geral e não os detalhes.

Se ainda tiver dúvidas marcamos uma chamada que te explico. 

## sobre `python-telegram-bot` 
Agora é um momento crucial para você começar a focar em resolver o problema em partes e não querer aprender tudo de uma vez só.

Não tente absorver tudo da documentação de uma única vez. 

Você chegou a ver esse tópico aqui chamado [Quick Start](https://github.com/python-telegram-bot/python-telegram-bot#quick-start), que te direciona para essa [Tutorial: Your first Bot](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-Your-first-Bot)?

**Comment by camilaccb** [comment]
Foi por esse quick start que eu comecei mesmo! Vou olhar o material sobre apis!

**Comment by camilaccb** [comment]
@HenriqueAJNB Antes de fazer o commit referente a essa atividade lembrei do ponto referente ao token do bot do telegram.  Dei uma pesquisa e vi umas 2 formas de fazer (devem ter mais também). Existe alguma boa prática relacionado a isso? 

Sobre as formas que eu encontrei:

- Criar uma variável de ambiente no OS e utilizar no python
- Criar um outro script de credencial e importar ele no script principal, "chamando" o token que  agente precisa. Esse novo script seria incluido no .git ignore. Aqui pensei que esse script poderia estar dentro da pasta .venv que já tá sendo ignorada.

**Comment by HenriqueAJNB** [comment]
Existem alternativas melhores. Pesquisa pelo `python-dotenv`

**Comment by camilaccb** [comment]
Boa @HenriqueAJNB , consegui implementar aqui. Segui esse [tutorial](https://towardsdatascience.com/using-dotenv-to-hide-sensitive-information-in-python-77ab9dfdaac8).
