### ISSUE TITLE
Makes the bot receive an image

### ISSUE THREAD

**Issue by HenriqueAJNB** [camilaccb/Automation-read-invoices#5]
- Create a simple app that receives an image and saves it into the folder.

https://github.com/python-telegram-bot/python-telegram-bot

**Comment by camilaccb** [comment]
@HenriqueAJNB  consegui implementar essa parte, a documentação é excelente. A parte que me gerou um pouco mais de dúvida foi a utilização da` pathlib` , mas quando entendi fluiu bem.
Só tive uma dúvida, estou baixando os arquivos para uma pasta chamada `Documents`  no diretório raiz do projeto. Essa pasta pode ser ignorada no commit também?  Ao meu ver não faz sentido ficar commitando essa pasta com arquivos. 

![image](https://user-images.githubusercontent.com/98741510/212550716-e6a2e0f5-06b5-4f12-a0e4-6cb426bd8de0.png)

**Comment by HenriqueAJNB** [comment]
Se não for documentação de uso da aplicação, não precisa subir. Creio que é só uma documentação pra você aprender, não?

**Comment by camilaccb** [comment]
São os documentos baixados pelo bot!

**Comment by HenriqueAJNB** [comment]
Ah, então não! São documentos confidenciais, contendo inclusive o número da nota fiscal. Não devem subir para o GitHub mesmo não. 

Sugiro colocar `documents/` no `.gitignore`. Mais a frente podemos modificar o código pra ele direcionar para uma pasta do Google Drive, para que os documentos não fiquem perdidos em uma instância em nuvem do Google Cloud.

**Comment by camilaccb** [comment]
Vou dar uma fuçada aqui em como fazer isso! Vou deixar a issue aberta caso tenha alguma dúvida nesse sentido
